apiVersion: v1
kind: Pod
metadata:
  name: app-environment
  namespace: upskill
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["/bin/sh","-c"]
    args: [ "echo AUTH_ENABLED=$AUTH_ENABLED && echo HTTP_LISTEN_PORT=$HTTP_LISTEN_PORT && sleep 3600" ]
    envFrom:
    - configMapRef:
        name: app-env-config
