apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: upskill
spec:
  clusterIP: None  # Makes this a Headless Service
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
