apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: upskill
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80      # Port exposed by the Service
    targetPort: 80 # Port the container listens on
  type: ClusterIP
