apiVersion: batch/v1
kind: Job
metadata:
  name: print-hostname-job
  namespace: upskill
spec:
  template:
    metadata:
      labels:
        app: print-hostname
    spec:
      containers:
      - name: print-hostname
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["hostname"]
      restartPolicy: Never
  backoffLimit: 4
