apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: upskill
  name: configmap-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: upskill
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
