apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  namespace: upskill
spec:
  containers:
  - name: python-container
    image: python:3.10-slim
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - name: kube-api-access
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  volumes:
  - name: kube-api-access
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
