apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  namespace: upskill
spec:
  containers:
  - name: python-container
    image: python:3.10-slim
    env:
    - name: LOG_LEVEL
      value: "INFO" # Default value of LOG_LEVEL
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "LOG_LEVEL=$LOG_LEVEL";
        sleep 1;
      done;
    volumeMounts:
    - name: kube-api-access
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
  volumes:
  - name: kube-api-access
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          name: kube-root-ca.crt
          items:
          - key: ca.crt
            path: ca.crt
      - downwardAPI:
          items:
          - path: namespace
            fieldRef:
              fieldPath: metadata.namespace
