apiVersion: v1
kind: Pod
metadata:
  name: app-command-args
  namespace: upskill
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args:
    - echo AUTH_ENABLED=$(AUTH_ENABLED) && echo HTTP_LISTEN_PORT=$(HTTP_LISTEN_PORT) && sleep 3600
    env:
    - name: AUTH_ENABLED
      valueFrom:
        configMapKeyRef:
          name: app-cli-config
          key: auth_enabled
    - name: HTTP_LISTEN_PORT
      valueFrom:
        configMapKeyRef:
          name: app-cli-config
          key: http_listen_port
