apiVersion: v1
kind: Pod
metadata:
  name: nginx-init
  namespace: upskill
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo '<h1>Hello from Init Container!</h1>' > /usr/share/nginx/html/index.html;
      echo 'Custom page set by InitContainer.'
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    emptyDir: {}
